### ISSUE TITLE
SQLTableDependency 6.2.0 not working with SqlTableDependencyFilter 1.2.0

### ISSUE THREAD

**Issue by IvanSule** [christiandelbianco/monitor-table-change-with-sqltabledependency#52]
Hi. Have following compiler error on SqlTableDependencyFilter constructor:
The type 'IModelToTableMapper<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'TableDependency, Version=5.0.0.0, Culture=neutral, PublicKeyToken=997305cc1a8bb802'.
When using version SQLTableDependency 6.1.0 no errors.
P.S. I have 2 questions (please forgive me if this is not a right place to ask):
1. How to configure IIS hosting WCF that uses SQLTableDependency? Perhaps set idle timeout to 0 and schedule app pool recycle to happen each night?
2. Is it possible to use SQLTableDependency on db being automatically backed up every night? Did not understand related remark completely.

**Comment by christiandelbianco** [comment]
Hi.
I updated the SqlTableDependencyFilter GitHub repository. Now compilation error is not anymore present.
Also, concerning your questions:

1. Have a look at example https://github.com/christiandelbianco/Monitor-table-change-with-WPF-WCF-sqltabledependency 
2. Is it possible to use SQLTableDependency on db being automatically backed...? NO

**Comment by IvanSule** [comment]
Thanks.
Regarding hosting on IIS, I do not see anything related on your link. Except that WCF runs as singleton. But I have WCF running instance per call. And need tabledependency closed as soon as call is ended, disposed. Also, I cannot catch when objects are destroyed in SQL. I am quite sure they are when IIS is restarted, bot not destroyed when app pool is recycled. Can you be more specific when objects are destroyed? I have implemented dispose methods as in your example but objects stay in SQL.
When DB is backed up, objects are destroyed, or something else happens? Should be logical to expect that DB is backed up.

**Comment by christiandelbianco** [comment]
"I have WCF running instance per call"..."And need tabledependency closed as soon as call is ended, disposed."

In this case i think that you do not need SqlTableDependency. A WCF call state for few seconds, while SqlTableDependency is used to **constantly** keep tracks of record changes.

**Comment by IvanSule** [comment]
We have tricky scenario. WCF receives request, inserts a row in table and then waits for row update which is done by different party asynchronously. I wanted to use SQLTableDependency instead of polling db for row change. It really does awesome job.
Btw., I guess there are some reasons not using it on db being backed up, but db backup is in most cases needed. I guess you will agree.

**Comment by christiandelbianco** [comment]
You can do what you want. Fact is that i think you are not correctly use SqlTableDependency. Every WCF request generate QUEUE, SERVICE BROKER, STORED PROCEDURE and TRIGGER, just to be disposed few second later. In any case, it is your decision.
